# Agent Marketplace Deployment Workflow
# This workflow handles the deployment of both frontend and backend components
# to production using Docker and GitHub Actions.
#
# Required GitHub Secrets:
# ----------------------
# DOCKERHUB_USERNAME: Your Docker Hub username
# DOCKERHUB_TOKEN: Your Docker Hub access token
# PROD_SERVER_HOST: Production server hostname/IP
# PROD_SERVER_USER: Production server SSH username
# PROD_SERVER_KEY: Production server SSH private key
# SLACK_WEBHOOK_URL: Slack webhook URL for deployment notifications
#
# Deployment Process:
# ------------------
# 1. Builds and pushes Docker images for both frontend and backend
# 2. Deploys to production server (only on main branch pushes)
# 3. Sends Slack notifications about deployment status
#
# Note: This workflow runs on both push and pull requests to main branch,
# but actual deployment to production only occurs on direct pushes to main.

name: Deploy Agent Marketplace

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: |
            inferloop/agent-marketplace-backend:${{ github.sha }}
            inferloop/agent-marketplace-backend:latest
          cache-from: type=registry,ref=inferloop/agent-marketplace-backend:latest
          cache-to: type=inline

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: frontend/Dockerfile
          push: true
          tags: |
            inferloop/agent-marketplace-frontend:${{ github.sha }}
            inferloop/agent-marketplace-frontend:latest
          cache-from: type=registry,ref=inferloop/agent-marketplace-frontend:latest
          cache-to: type=inline

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_KEY }}
          port: 22
          script: |
            cd /opt/agent-marketplace
            git pull origin main
            docker-compose pull
            docker-compose up -d --force-recreate
            docker system prune -f

      - name: Notify Slack
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: '#deployments'
          username: 'Agent Marketplace Deploy'
          icon_emoji: ':rocket:'
          text: 'Deployment completed for commit ${{ github.sha }}'
          payload: |
            {
              "attachments": [
                {
                  "color": "#36a64f",
                  "title": "Agent Marketplace Deployment",
                  "title_link": ${{ github.event.head_commit.url }},
                  "text": "Deployed commit ${{ github.sha }} to production",
                  "footer": "GitHub Actions",
                  "footer_icon": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                  "ts": ${{ github.event.head_commit.timestamp }}
                }
              ]
            }